# Site settings
title: Evgeny Kuznetsov
email: e.kuznetsov@freeuni.edu.ge
url: https://rmi.tsu.ge/eng/staffdep.htm#mathl
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "algebra-in-logic, category-theory-in-logic, topology-in-logic"
skills: "Mathematician & Back End Developer"
meta_author: Evgeny Kuznetsov

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
# disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Evgeny Kuznetsov
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: 
  - title: linkedin
    url: https://www.linkedin.com/in/evgeny-kuznetsov-b479ba114/


# Postal address (add as many lines as necessary)
address:
  - line: 2, Merab Aleksidze II Lane
  - line: Tbilisi 0193, Georgia

# Credits content
credits: 'Theme by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
